# Sprint 48 — GLM Standardized Evaluation vs Frozen Baseline (crash-proof v3)

Resolves the Sprint 47 exploration (five inconsistent evals, no recommendation) with ONE standardized run against ONE documented baseline.

| # | Acceptance criterion | Section |
|---|---|---|
| 1 | Document exact baseline config (model variant, quantization, prompt template) | §1 |
| 2 | FLORES-200 devtest: one fixed GLM checkpoint, one fixed quantization, vs baseline | §2–§5 |
| 3 | Blind human review: ≥100 eng→Cantonese (authenticity) + ≥100 eng→Mandarin (quality) | §7 |
| 4 | Pipeline fit: QLoRA compat, tokenizer efficiency on Cantonese particles, multi-LoRA | §8 |
| 5 | Final adopt-alongside / replace / rule-out recommendation with evidence | §9 |
| 6 | Push notebook + results to the shared pod repo | §10 |

**Why previous versions crashed, and what changed:**
- The Sprint-47 install forced `numpy==1.26.4` + `pandas==2.2.2` onto a Colab image whose preinstalled torch/pyarrow/scipy are now built against numpy 2 → binary mismatch → dead session. **v3 never touches numpy/pandas/pyarrow/protobuf.** Only self-contained packages are installed. **No runtime restarts, ever.**
- **COMET is optional and sandboxed** (its dependency chain is what dragged numpy down). chrF is the always-works primary metric; if COMET installs cleanly it augments the scores, if not the eval completes without it.
- **Per-batch checkpointing**: every generated batch is written to disk immediately. If the session dies from RAM/GPU pressure, rerun §4 and it resumes mid-direction — nothing is retranslated.
- One model in VRAM at a time, explicit cleanup between; **left padding** fix retained (Sprint 47 right-padded, corrupting batched baseline outputs).

**Runtime:** any GPU (T4 is enough). Optionally mount Drive so results survive disconnects.

In [1]:
#@title §0 · Setup — installs (NO numpy/pandas changes, NO restart), GPU, workspace
import os
os.environ["USE_TF"] = "0"

# Only self-contained packages; Colab's numpy/pandas/torch stack stays untouched.
%pip install -q sacrebleu "peft>=0.13" bitsandbytes accelerate sentencepiece tiktoken

import importlib
for m in ["numpy","pandas","torch","transformers","sacrebleu","peft","bitsandbytes"]:
    try:
        print(f"{m:13s}", getattr(importlib.import_module(m), "__version__", "?"))
    except Exception as e:
        print(f"{m:13s} FAILED: {e}")

import torch, pandas as pd, json, pathlib, gc
assert torch.cuda.is_available(), "Runtime → Change runtime type → GPU, then rerun."
print("GPU:", torch.cuda.get_device_name(0),
      f"| VRAM {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB")

MOUNT_DRIVE = False  #@param {type:"boolean"}
if MOUNT_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    WORKDIR = "/content/drive/MyDrive/glm-eval-sprint48"
else:
    WORKDIR = "/content/glm-eval-sprint48"
for d in ("configs","outputs","human_review","docs"):
    pathlib.Path(WORKDIR, d).mkdir(parents=True, exist_ok=True)
os.chdir(WORKDIR)
print("workdir:", os.getcwd(),
      "(persists on Drive)" if MOUNT_DRIVE else "(ephemeral — enable MOUNT_DRIVE to survive disconnects)")

def free_vram():
    gc.collect(); torch.cuda.empty_cache()
    print(f"VRAM in use: {torch.cuda.memory_allocated()/1e9:.2f} GB")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 68.7 MB/s eta 0:00:00
numpy         2.0.2
pandas        2.2.2
torch         2.11.0+cu128
transformers  5.13.1
sacrebleu     2.6.0
peft          0.19.1
bitsandbytes  0.50.0
GPU: NVIDIA A100-SXM4-40GB | VRAM 42.4 GB
workdir: /content/glm-eval-sprint48 (ephemeral — enable MOUNT_DRIVE to survive disconnects)

## §1 · Frozen baseline configuration — the setup of record *(criterion 1)*

One fixed GLM checkpoint, one fixed quantization, one prompt template — frozen, hashed, and stamped into every output file. Changing anything = new `config_version` + full rerun.

In [2]:
#@title §1 · Freeze + document the config
import hashlib, subprocess, sys

FROZEN = {
  "config_version": "1.0.0",
  "sprint": "48 (supersedes Sprint 47 exploration)",
  "frozen_by": "CHANGE_ME",                       # <-- your name
  "baseline":  {"model_id": "Qwen/Qwen2.5-7B-Instruct", "revision": "main"},
  "candidate": {"model_id": "zai-org/GLM-4-9B-0414",    "revision": "main"},  # THE fixed GLM checkpoint
  "quantization": {"method": "bnb-nf4", "bits": 4, "double_quant": True,
                   "note": "ONE method, both models, entire eval"},
  "generation": {"do_sample": False, "max_new_tokens": 256,
                 "batch_size": 4, "padding_side": "left", "seed": 42},
  "data": {"dataset": "FLORES-200 devtest (Meta public tarball)",
           "n_sentences": 200,                    # 1012 = full devtest for final sign-off
           "directions": [["eng_Latn","yue_Hant"], ["eng_Latn","zho_Hans"],
                          ["yue_Hant","eng_Latn"], ["zho_Hans","eng_Latn"]]},
  "metrics": {"primary": "sacrebleu chrF2 (always runs)",
              "secondary": "COMET-22 Unbabel/wmt22-comet-da (optional, sandboxed)"},
  "human_review": {"n_per_pair": 100, "sampling_seed": 7,
                   "pairs": ["eng_Latn->yue_Hant", "eng_Latn->zho_Hans"]},
}

LANGS = {
  "eng_Latn": "English",
  "yue_Hant": "Cantonese (written vernacular Cantonese, 粵語白話文, Traditional characters)",
  "zho_Hans": "Mandarin Chinese (Simplified characters)",
}

def make_prompt(src_code, tgt_code, text):
    """THE frozen prompt template."""
    src_name, tgt_name = LANGS[src_code], LANGS[tgt_code]
    instr = (f"Translate the following {src_name} sentence into {tgt_name}. "
             f"Output ONLY the translation, with no explanation, no romanization, "
             f"and no quotation marks.")
    if tgt_code == "yue_Hant":
        instr += (" The translation must be natural written vernacular Cantonese "
                  "as used in Hong Kong (using words like 嘅、喺、唔、佢 where natural), "
                  "NOT Standard Written Chinese.")
    return f"{instr}\n\n{src_name}: {text}\n{tgt_name}:"

FROZEN["prompt_template"] = make_prompt("eng_Latn", "yue_Hant", "{source}")
pathlib.Path("configs/baseline.json").write_text(json.dumps(FROZEN, indent=2, ensure_ascii=False))
FP = hashlib.sha256(json.dumps(FROZEN, sort_keys=True, ensure_ascii=False).encode()).hexdigest()[:12]

freeze = subprocess.run([sys.executable, "-m", "pip", "freeze"], capture_output=True, text=True).stdout
keep = ("torch","transformers","sacrebleu","peft","bitsandbytes","accelerate","numpy","pandas","comet")
pathlib.Path("configs/environment.txt").write_text(
    "\n".join(l for l in freeze.splitlines() if any(k in l.lower() for k in keep)))

if FROZEN["frozen_by"] == "CHANGE_ME":
    print("NOTE: fill in frozen_by + pin revisions to commit SHAs before final sign-off.\n")
print("CONFIG FINGERPRINT:", FP, "→ stamped into every output file")
print("baseline :", FROZEN["baseline"]["model_id"])
print("candidate:", FROZEN["candidate"]["model_id"], "| quant:", FROZEN["quantization"]["method"])
print("\n--- frozen prompt template (eng→yue instance) ---\n" + FROZEN["prompt_template"])

NOTE: fill in frozen_by + pin revisions to commit SHAs before final sign-off.

CONFIG FINGERPRINT: 7f05cd7dba78 → stamped into every output file
baseline : Qwen/Qwen2.5-7B-Instruct
candidate: zai-org/GLM-4-9B-0414 | quant: bnb-nf4

--- frozen prompt template (eng→yue instance) ---
Translate the following English sentence into Cantonese (written vernacular Cantonese, 粵語白話文, Traditional characters). Output ONLY the translation, with no explanation, no romanization, and no quotation marks. The translation must be natural written vernacular Cantonese as used in Hong Kong (using words like 嘅、喺、唔、佢 where natural), NOT Standard Written Chinese.

English: {source}
Cantonese (written vernacular Cantonese, 粵語白話文, Traditional characters):

## §2 · FLORES-200 devtest *(criterion 2)* — Meta public tarball, no auth

In [3]:
#@title §2 · Load FLORES-200 devtest
import tarfile, urllib.request

N_SENTENCES = FROZEN["data"]["n_sentences"]   # 200 now; 1012 = full devtest for final run
FLORES_DIR = "/content/flores200_dataset"
if not os.path.exists(FLORES_DIR):
    print("Downloading FLORES-200 (~25 MB)…")
    urllib.request.urlretrieve("https://dl.fbaipublicfiles.com/nllb/flores200_dataset.tar.gz",
                               "/content/flores200.tar.gz")
    with tarfile.open("/content/flores200.tar.gz") as tf:
        tf.extractall("/content")

def load_flores_devtest(code):
    with open(f"{FLORES_DIR}/devtest/{code}.devtest", encoding="utf-8") as f:
        return [l.rstrip("\n") for l in f]

flores = {code: load_flores_devtest(code) for code in LANGS}
n_total = len(flores["yue_Hant"])
assert all(len(v) == n_total for v in flores.values()), "FLORES splits misaligned!"
if N_SENTENCES:
    flores = {k: v[:N_SENTENCES] for k, v in flores.items()}
print(f"Loaded {len(flores['yue_Hant'])} parallel sentences per language "
      f"(need >= {FROZEN['human_review']['n_per_pair']} for the human review).")
for k in flores:
    print(f"  {k}: {flores[k][0][:70]}…")

Downloading FLORES-200 (~25 MB)…

/tmp/ipykernel_834/169307473.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tf.extractall("/content")

Loaded 200 parallel sentences per language (need >= 100 for the human review).
  eng_Latn: "We now have 4-month-old mice that are non-diabetic that used to be di…
  yue_Hant: 他補充說：「我們現在有 4 個月大的老鼠，牠們現在沒有糖尿病，但過去曾患糖尿病。」…
  zho_Hans: 他补充道：“我们现在有 4 个月大没有糖尿病的老鼠，但它们曾经得过该病。”…

## §3 · Model + generation helpers (frozen quantization, LEFT padding, per-batch checkpoints)

In [4]:
#@title §3 · Helpers
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

DTYPE = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
BATCH_SIZE = FROZEN["generation"]["batch_size"]
MAX_NEW_TOKENS = FROZEN["generation"]["max_new_tokens"]
torch.manual_seed(FROZEN["generation"]["seed"])
print("compute dtype:", DTYPE)

def load_model(model_id, revision="main"):
    tok = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True, revision=revision)
    tok.padding_side = "left"                     # decoder-only batching fix
    if tok.pad_token_id is None:
        tok.pad_token = tok.eos_token
    model = AutoModelForCausalLM.from_pretrained(
        model_id, trust_remote_code=True, device_map="auto", revision=revision,
        low_cpu_mem_usage=True,
        quantization_config=BitsAndBytesConfig(   # THE one frozen quantization
            load_in_4bit=True, bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True, bnb_4bit_compute_dtype=DTYPE)).eval()
    return tok, model

@torch.no_grad()
def translate_direction(tok, model, src, tgt, tag):
    """Generates with a PER-BATCH checkpoint: outputs/{tag}_{src}_{tgt}.json is
    rewritten after every batch, and resumed from on rerun — a dead session
    costs at most one batch."""
    path = f"outputs/{tag}_{src}_{tgt}.json"
    n = len(flores[src])
    res = {"src": flores[src], "ref": flores[tgt], "hyp": [],
           "config_fingerprint": FP}
    if os.path.exists(path):
        try:
            old = json.load(open(path, encoding="utf-8"))
            if old.get("config_fingerprint") == FP and len(old.get("hyp", [])) <= n:
                res["hyp"] = old["hyp"]
        except Exception:
            pass
    if len(res["hyp"]) >= n:
        print(f"[{tag}] {src}->{tgt}: complete ({n}) — skipping")
        return res
    start = len(res["hyp"])
    if start:
        print(f"[{tag}] {src}->{tgt}: resuming from sentence {start}")
    prompts = [make_prompt(src, tgt, s) for s in flores[src]]
    for i in range(start, n, BATCH_SIZE):
        chunk = prompts[i:i+BATCH_SIZE]
        msgs = [[{"role": "user", "content": p}] for p in chunk]
        enc = tok.apply_chat_template(msgs, add_generation_prompt=True, tokenize=True,
                                      return_tensors="pt", return_dict=True,
                                      padding=True).to(model.device)
        gen = model.generate(**enc, max_new_tokens=MAX_NEW_TOKENS, do_sample=False,
                             pad_token_id=tok.pad_token_id)
        for out_ids in gen:
            txt = tok.decode(out_ids[enc["input_ids"].shape[1]:],
                             skip_special_tokens=True).strip()
            res["hyp"].append(txt.split("\n")[0].strip().strip(chr(34) + "\u201c\u201d"))
        with open(path, "w", encoding="utf-8") as f:      # checkpoint every batch
            json.dump(res, f, ensure_ascii=False)
        if (i // BATCH_SIZE) % 10 == 0:
            print(f"  {min(i+BATCH_SIZE, n)}/{n}  {res['hyp'][-1][:44]}")
    print(f"[{tag}] {src}->{tgt}: done -> {path}")
    return res

compute dtype: torch.bfloat16

## §4 · Run both systems, all four directions *(criterion 2)*

If the session dies here, just rerun this cell — it reloads the model and resumes from the last saved batch.

In [5]:
#@title §4 · Generate translations (resumable)
DIRECTIONS = [tuple(d) for d in FROZEN["data"]["directions"]]

def run_model(spec, tag):
    n = len(flores["eng_Latn"])
    done = all(os.path.exists(f"outputs/{tag}_{s}_{t}.json") and
               len(json.load(open(f"outputs/{tag}_{s}_{t}.json", encoding="utf-8")).get("hyp", [])) >= n
               for s, t in DIRECTIONS)
    results = {}
    if done:
        for s, t in DIRECTIONS:
            results[f"{s}->{t}"] = json.load(open(f"outputs/{tag}_{s}_{t}.json", encoding="utf-8"))
        print(f"[{tag}] all directions complete — model not loaded")
        return results
    print(f"\n===== Loading {spec['model_id']} =====")
    tok, model = load_model(spec["model_id"], spec.get("revision", "main"))
    for s, t in DIRECTIONS:
        print(f"\n--- {tag}: {s}->{t} ---")
        results[f"{s}->{t}"] = translate_direction(tok, model, s, t, tag)
    del model, tok
    free_vram()
    return results

all_results = {}
all_results["glm"]  = run_model(FROZEN["candidate"], "glm")
all_results["qwen"] = run_model(FROZEN["baseline"], "qwen")

===== Loading zai-org/GLM-4-9B-0414 =====

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/689 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/4.17k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 20.0MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/601 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/1.01k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/43.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/523 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

--- glm: eng_Latn->yue_Hant ---
  4/200  個禮拜一，瑞典學院文學獎委員會常任秘書Sara Danius喺瑞典Sveriges Ra
  44/200  802.11n 嘅速度遠遠快過佢哋前身，最高理論傳輸率係 600Mbit/s。
  84/200  九街喺颱風卡特里娜期間見過洪水高達二十呎，而家係浸到腰咁高，因為附近嘅堤壩冇咗。
  124/200  呢個64歲嘅貨車司機喺意外入面冇受傷。
  164/200  官員確認選民身份之後，選民將信封放入選票箱並簽署選票冊。
[glm] eng_Latn->yue_Hant: done -> outputs/glm_eng_Latn_yue_Hant.json

--- glm: eng_Latn->zho_Hans ---
  4/200  周一，瑞典学院诺贝尔文学奖评委会常任秘书萨拉·丹尼乌斯在瑞典斯韦登广播电台的一档广播节目
  44/200  802.11n的传输速度远比其前身快得多，最大理论吞吐量为600Mbit/s。
  84/200  九区在卡特里娜飓风中遭遇过高达20英尺的洪水，目前由于附近堤坝漫顶，水位已及腰部。
  124/200  那位64岁的卡车司机在车祸中未受伤。
  164/200  官员核实选民身份后，选民将信封投入票箱并签署选民名册。
[glm] eng_Latn->zho_Hans: done -> outputs/glm_eng_Latn_zho_Hans.json

--- glm: yue_Hant->eng_Latn ---
  4/200  On Monday, the Permanent Secretary of the Sw
  44/200  The speed of 802.11n greatly surpasses its p
  84/200  During Hurricane Katrina's invasion, the flo
  124/200  This 64-year-old truck driver was not injure
  164/200  After election workers verify the voters' id
[glm] yue_Hant->eng_Latn: done -> outputs/glm_yue_Hant_eng_Latn.json

--- glm: zho_Hans->eng_Latn ---
  4/200  On Monday, Sara Danius, the acting secretary
  44/200  The speed of 802.11n is much faster than pre
  84/200  When Hurricane Katrina struck, the floodwate
  124/200  This 64-year-old truck driver was not injure
  164/200  After officials verify the voter's identity,
[glm] zho_Hans->eng_Latn: done -> outputs/glm_zho_Hans_eng_Latn.json
VRAM in use: 0.01 GB

===== Loading Qwen/Qwen2.5-7B-Instruct =====

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

--- qwen: eng_Latn->yue_Hant ---
  4/200  星期一，莎拉·丹尼治，瑞典學院文學獎評委會永久秘書，喺瑞典嘅瑞典廣播電台嘅.ToShor
  44/200  802.11n嘅速度比佢乸代快好多，最大理論吞吐量系600Mbit/s。
  84/200  第九區既水浸度揸到二十尺高，-Cs-嘅度近嘅壩冚已經頂住水咗，現在度腰埋水。
  124/200  卡車駕駛人，係六十四歲，意外𠮶陣喺咪受傷。
  164/200  官員核對選民身份之后，選民將信封投入票箱并簽名登记。
[qwen] eng_Latn->yue_Hant: done -> outputs/qwen_eng_Latn_yue_Hant.json

--- qwen: eng_Latn->zho_Hans ---
  4/200  周一，瑞典文学院诺贝尔文学奖评审委员会的常任秘书莎拉·丹尼乌斯在瑞典广播公司的一档电台节
  44/200  802.11n的传输速度比其 predecessor 的速度快很多，理论最大吞吐量为60
  84/200  第九wards，飓风卡特里娜期间曾遭受高达20英尺的洪水侵袭，目前由于附近堤坝决堤，水位
  124/200  这位64岁的卡车司机在车祸中没有受伤。
  164/200  官员核实选民身份后，选民将信封投入票箱并签名登记。
[qwen] eng_Latn->zho_Hans: done -> outputs/qwen_eng_Latn_zho_Hans.json

--- qwen: yue_Hant->eng_Latn ---
  4/200  On Monday, permanent secretary of the Swedis
  44/200  The speed of 802.11n greatly surpasses its p
  84/200  During Hurricane Katrina's invasion, the flo
  124/200  This 64-year-old truck driver was not injure
  164/200  After the staff verify the voter's identity,
[qwen] yue_Hant->eng_Latn: done -> outputs/qwen_yue_Hant_eng_Latn.json

--- qwen: zho_Hans->eng_Latn ---
  4/200  On Monday, Sara Daniels, permanent secretary
  44/200  The speed of 802.11n is significantly faster
  84/200  When Hurricane Katrina hit, the water level
  124/200  The 64-year-old truck driver was not injured
  164/200  After officials verify the voter's identity,
[qwen] zho_Hans->eng_Latn: done -> outputs/qwen_zho_Hans_eng_Latn.json
VRAM in use: 0.01 GB

## §5 · Automatic metrics *(criterion 2)*

**chrF always runs** (sacrebleu is pure Python — cannot break the runtime). The COMET cell below is fully sandboxed: it tries to install/score, and if its dependency chain conflicts with Colab's current image it fails *gracefully* — the eval completes on chrF.

In [6]:
#@title §5a · chrF (primary — always works)
import sacrebleu

rows = []
for tag, results in all_results.items():
    for d, res in results.items():
        chrf = sacrebleu.corpus_chrf(res["hyp"], [res["ref"]]).score
        rows.append({"model": tag, "direction": d, "chrF": round(chrf, 2)})
        print(f"{tag:5s} {d:22s} chrF={chrf:.2f}")
score_df = pd.DataFrame(rows)
score_df.to_csv("outputs/scores.csv", index=False)
score_df

glm   eng_Latn->yue_Hant     chrF=21.22
glm   eng_Latn->zho_Hans     chrF=37.02
glm   yue_Hant->eng_Latn     chrF=57.13
glm   zho_Hans->eng_Latn     chrF=58.23
qwen  eng_Latn->yue_Hant     chrF=14.71
qwen  eng_Latn->zho_Hans     chrF=35.53
qwen  yue_Hant->eng_Latn     chrF=57.09
qwen  zho_Hans->eng_Latn     chrF=57.61

  model           direction   chrF
0   glm  eng_Latn->yue_Hant  21.22
1   glm  eng_Latn->zho_Hans  37.02
2   glm  yue_Hant->eng_Latn  57.13
3   glm  zho_Hans->eng_Latn  58.23
4  qwen  eng_Latn->yue_Hant  14.71
5  qwen  eng_Latn->zho_Hans  35.53
6  qwen  yue_Hant->eng_Latn  57.09
7  qwen  zho_Hans->eng_Latn  57.61

In [7]:
#@title §5b · COMET-22 (optional, sandboxed — safe to skip)
RUN_COMET = True  #@param {type:"boolean"}
COMET_OK = False
if not RUN_COMET:
    print("COMET skipped. chrF remains the automatic metric.")
else:
    try:
        %pip install -q "unbabel-comet>=2.2.0"
        import numpy as _np
        _ = _np.random.RandomState                       # verify numpy still healthy
        from comet import download_model, load_from_checkpoint
        cm = load_from_checkpoint(download_model("Unbabel/wmt22-comet-da"))
        comets = []
        for _, r in score_df.iterrows():
            res = all_results[r["model"]][r["direction"]]
            data = [{"src": s, "mt": h, "ref": rf}
                    for s, h, rf in zip(res["src"], res["hyp"], res["ref"])]
            cs = float(cm.predict(data, batch_size=8, gpus=1).system_score)
            comets.append(round(cs, 4))
            print(f"{r['model']:5s} {r['direction']:22s} COMET-22={cs:.4f}")
        score_df["COMET-22"] = comets
        score_df.to_csv("outputs/scores.csv", index=False)
        COMET_OK = True
        del cm; free_vram()
    except Exception as e:
        print(f"COMET unavailable on this runtime ({type(e).__name__}: {str(e)[:120]}).")
        print("Continuing on chrF — this does NOT block the evaluation.")
score_df

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 5.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.0/91.0 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.4/101.4 kB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 42.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 119.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.2/295.2 kB 29.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 59.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.7/529.7 kB 45.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 136.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
grain 0.2.18 requires protobuf>=5.28.3, but you have protobuf 4.25.9 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 4.25.9 which is incompatible.
tensorflow 2.20.0 requires protobuf>=5.28.0, but you have protobuf 4.25.9 which is incompatible.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 4.25.9 which is incompatible.
COMET unavailable on this runtime (ValueError: Backend should be defined in the BACKENDS_MAPPING. Offending backend: tensorflow_text).
Continuing on chrF — this does NOT block the evaluation.

  model           direction   chrF
0   glm  eng_Latn->yue_Hant  21.22
1   glm  eng_Latn->zho_Hans  37.02
2   glm  yue_Hant->eng_Latn  57.13
3   glm  zho_Hans->eng_Latn  58.23
4  qwen  eng_Latn->yue_Hant  14.71
5  qwen  eng_Latn->zho_Hans  35.53
6  qwen  yue_Hant->eng_Latn  57.09
7  qwen  zho_Hans->eng_Latn  57.61

## §6 · Cantonese authenticity screen *(feeds criterion 3)*

Marker-based screen (嘅咗喺哋… vs 的了在不…). Comparative signal + stratification aid; the blind human review (§7) is the authoritative judgment.

In [8]:
#@title §6 · Authenticity classification + examples
import re

CANTO_MARKERS = set("嘅咗喺哋嗰啲嘢冇唔諗畀攞咁乜嚟緊晒囉㗎啩喎咩")
CANTO_BIGRAMS = ["點解","而家","琴日","聽日","咩嘢","邊個","邊度","得閒",
                 "鍾意","好似","唔係","係咪","冇得","俾佢","睇吓","諗吓"]
MANDO_MARKERS = set("的了在不沒他她它們這那说說給")
MANDO_BIGRAMS = ["什麼","甚麼","怎麼","為什麼","喜歡","現在","昨天","明天",
                 "知道","沒有","是的","可以","他們","她們"]

def han_len(t):
    return max(1, len(re.findall(r"[\u4e00-\u9fff\u3400-\u4dbf]", t)))

def classify(text, c_thresh=0.03, m_thresh=0.05):
    n = han_len(text)
    c = (sum(text.count(ch) for ch in CANTO_MARKERS) +
         2*sum(text.count(b) for b in CANTO_BIGRAMS)) / n
    m = (sum(text.count(ch) for ch in MANDO_MARKERS) +
         2*sum(text.count(b) for b in MANDO_BIGRAMS)) / n
    if c >= c_thresh and c > m*0.5: return "cantonese"
    if m >= m_thresh and c < c_thresh: return "mandarin-like"
    if c > 0 and m > 0: return "mixed"
    return "neutral"

qual_rows = []
for tag in all_results:
    res = all_results[tag]["eng_Latn->yue_Hant"]
    labels = [classify(h) for h in res["hyp"]]
    n = len(labels)
    qual_rows.append({"model": tag,
        "% genuine Cantonese": round(100*labels.count("cantonese")/n, 1),
        "% Mandarin-in-Trad": round(100*labels.count("mandarin-like")/n, 1),
        "% mixed": round(100*labels.count("mixed")/n, 1),
        "% neutral": round(100*labels.count("neutral")/n, 1)})
qual_df = pd.DataFrame(qual_rows)
qual_df.to_csv("outputs/cantonese_authenticity.csv", index=False)
print(qual_df.to_string(index=False))
for tag in all_results:
    res = all_results[tag]["eng_Latn->yue_Hant"]
    bad = [(s,h) for s,h in zip(res["src"], res["hyp"]) if classify(h)=="mandarin-like"][:2]
    print(f"\n[{tag}] Mandarin-in-Trad examples ({len(bad)} shown):")
    for s,h in bad:
        print(f"  SRC {s[:60]}\n  HYP {h[:70]}")

model  % genuine Cantonese  % Mandarin-in-Trad  % mixed  % neutral
  glm                 93.5                 0.5      0.5        5.5
 qwen                 81.5                 1.5      3.0       14.0

[glm] Mandarin-in-Trad examples (1 shown):
  SRC This will allow it to be backwards compatible with 802.11a,
  HYP 呢樣會令佢可以同 802.11a, 802.11b 同 802.11g 兼容，但係要基地台有雙無線電先得。

[qwen] Mandarin-in-Trad examples (2 shown):
  SRC Fourteen schools in Hawaii located on or near coastlines wer
  HYP 香港話版本：香港話既話，可以翻譯成：
  SRC Between 10:00-11:00 pm MDT, a fire was started by the inmate
  HYP 凌晨十時至十一時，囚犯在院場點火。

## §7 · Blind human review *(criterion 3)*

100 eng→yue + 100 eng→cmn rows; system A/B randomized **per row**; unblinding key saved separately and gitignored.

- `review_eng_yue.csv`: **authenticity 1–5** (1 = Mandarin in Traditional script … 5 = genuine HK written Cantonese) + **adequacy 1–5** per output, plus preference A/B/tie
- `review_eng_cmn.csv`: **adequacy 1–5** + **fluency 1–5** per output, plus preference A/B/tie

Download from the Files panel, have native reviewers fill them, re-upload, then run §7b.

In [9]:
#@title §7a · Build blinded review packs
import csv, random

rng = random.Random(FROZEN["human_review"]["sampling_seed"])
N = FROZEN["human_review"]["n_per_pair"]
key = {}
REVIEW_PAIRS = {"eng_yue": "eng_Latn->yue_Hant", "eng_cmn": "eng_Latn->zho_Hans"}
for short, d in REVIEW_PAIRS.items():
    glm, qwen = all_results["glm"][d], all_results["qwen"][d]
    sample = rng.sample(range(len(glm["hyp"])), min(N, len(glm["hyp"])))
    if len(sample) < N:
        print(f"NOTE: only {len(sample)} rows for {short} — raise n_sentences to >= {N}")
    if short == "eng_yue":
        header = ["row_id","english_source","output_A","output_B",
                  "A_authenticity_1to5","A_adequacy_1to5",
                  "B_authenticity_1to5","B_adequacy_1to5","preference_A_B_tie","notes"]
    else:
        header = ["row_id","english_source","output_A","output_B",
                  "A_adequacy_1to5","A_fluency_1to5",
                  "B_adequacy_1to5","B_fluency_1to5","preference_A_B_tie","notes"]
    with open(f"human_review/review_{short}.csv", "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f); w.writerow(header)
        for rid in sample:
            a_is_glm = rng.random() < 0.5
            key[f"{short}:{rid}"] = {"A": "glm" if a_is_glm else "qwen",
                                     "B": "qwen" if a_is_glm else "glm"}
            a = glm["hyp"][rid] if a_is_glm else qwen["hyp"][rid]
            b = qwen["hyp"][rid] if a_is_glm else glm["hyp"][rid]
            w.writerow([rid, glm["src"][rid], a, b] + [""]*(len(header)-4))
    print(f"wrote human_review/review_{short}.csv ({len(sample)} blinded rows)")
json.dump(key, open("human_review/UNBLIND_KEY_DO_NOT_OPEN.json", "w"), indent=2)
print("unblinding key saved (gitignored) — do NOT share with reviewers")

wrote human_review/review_eng_yue.csv (100 blinded rows)
wrote human_review/review_eng_cmn.csv (100 blinded rows)
unblinding key saved (gitignored) — do NOT share with reviewers

In [10]:
#@title §7b · Aggregate returned scores (safe anytime; PENDING until filled)
human_summary = {}
try:
    key = json.load(open("human_review/UNBLIND_KEY_DO_NOT_OPEN.json"))
    for short in REVIEW_PAIRS:
        rows_csv = list(csv.DictReader(open(f"human_review/review_{short}.csv", encoding="utf-8-sig")))
        scores = {"glm": {}, "qwen": {}}
        prefs = {"glm": 0, "qwen": 0, "tie": 0}
        n = 0
        for r in rows_csv:
            m = key.get(f"{short}:{r['row_id']}")
            if not m or not (r.get("preference_A_B_tie") or "").strip():
                continue
            n += 1
            p = r["preference_A_B_tie"].strip().upper()
            prefs[m[p] if p in ("A","B") else "tie"] += 1
            for lab in ("A","B"):
                for col, val in r.items():
                    if col and col.startswith(lab + "_") and (val or "").strip():
                        try:
                            scores[m[lab]].setdefault(col[2:], []).append(float(val))
                        except ValueError:
                            pass
        human_summary[short] = {"n_scored": n, "preferences": prefs,
            "mean_scores": {s: {k: round(sum(v)/len(v),2) for k,v in d.items()}
                            for s,d in scores.items() if d}}
    json.dump(human_summary, open("human_review/human_review_summary.json","w"), indent=2)
    if all(v["n_scored"] == 0 for v in human_summary.values()):
        print("Human review PENDING — rerun after reviewers return the CSVs.")
    print(json.dumps(human_summary, indent=2))
except FileNotFoundError as e:
    print("Run §7a first:", e)

Human review PENDING — rerun after reviewers return the CSVs.
{
  "eng_yue": {
    "n_scored": 0,
    "preferences": {
      "glm": 0,
      "qwen": 0,
      "tie": 0
    },
    "mean_scores": {}
  },
  "eng_cmn": {
    "n_scored": 0,
    "preferences": {
      "glm": 0,
      "qwen": 0,
      "tie": 0
    },
    "mean_scores": {}
  }
}

## §8 · Pipeline fit *(criterion 4)*

**8a — Tokenizer efficiency on Cantonese particles** (CPU, always safe).

In [11]:
#@title §8a · Tokenizer fertility on Cantonese particles
YUE_SAMPLES = ["佢哋而家喺度食緊嘢，唔知幾時先食完㗎。","呢啲嘢係我噚日買嘅，你睇下啱唔啱用啦。",
    "我冇話唔得㗎喎，不過你要俾多啲時間我諗下先。","咁樣搞法係唔掂嘅，梗係要搵人幫手啦。",
    "你哋傾掂咗未呀？傾掂咗就嚟呢度搵我哋啦。","嗰度啲嘢好好食㗎，你唔試下就走寶嘞。"]
CMN_SAMPLES = ["他们现在正在吃饭，不知道什么时候才能吃完。","这些东西是我昨天买的，你看看合不合用。",
    "我没有说不行，不过你要多给我一点时间考虑。","这样做是不行的，当然要找人帮忙了。"]
PARTICLES = list("嘅係喺咗唔冇啲嗰咁哋嚟俾睇諗搵㗎喎囉啫嘞咩")

tok_report = {}
for tag, spec in (("glm", FROZEN["candidate"]), ("qwen", FROZEN["baseline"])):
    tk = AutoTokenizer.from_pretrained(spec["model_id"], trust_remote_code=True)
    fert = lambda ss: round(sum(len(tk.encode(s, add_special_tokens=False)) for s in ss)
                            / sum(han_len(s) for s in ss), 3)
    per = {p: len(tk.encode(p, add_special_tokens=False)) for p in PARTICLES}
    tok_report[tag] = {"model": spec["model_id"],
        "fertility_yue": fert(YUE_SAMPLES), "fertility_cmn": fert(CMN_SAMPLES),
        "yue_vs_cmn_ratio": round(fert(YUE_SAMPLES)/fert(CMN_SAMPLES), 3),
        "multi_token_particles": {p:n for p,n in per.items() if n > 1}}
    print(f"[{tag}] {json.dumps(tok_report[tag], ensure_ascii=False)}")
print("\nEfficient ≈ glm fertility_yue <= 1.15 x qwen, few multi-token particles.")

[glm] {"model": "zai-org/GLM-4-9B-0414", "fertility_yue": 1.5, "fertility_cmn": 0.614, "yue_vs_cmn_ratio": 2.443, "multi_token_particles": {"嘅": 2, "喺": 2, "咗": 2, "冇": 2, "啲": 2, "嗰": 2, "咁": 2, "哋": 2, "嚟": 2, "俾": 2, "睇": 2, "諗": 2, "搵": 2, "㗎": 3, "喎": 2, "囉": 2, "啫": 2, "嘞": 2, "咩": 2}}
[qwen] {"model": "Qwen/Qwen2.5-7B-Instruct", "fertility_yue": 1.385, "fertility_cmn": 0.643, "yue_vs_cmn_ratio": 2.154, "multi_token_particles": {"嘅": 2, "喺": 2, "咗": 2, "冇": 2, "啲": 2, "嗰": 2, "咁": 2, "哋": 2, "嚟": 2, "諗": 2, "搵": 2, "㗎": 3, "喎": 2, "囉": 2}}

Efficient ≈ glm fertility_yue <= 1.15 x qwen, few multi-token particles.

**8b — QLoRA smoke test + multi-adapter hot-swap** (GPU): loads the frozen GLM checkpoint in 4-bit NF4, auto-discovers its linear-module names, attaches a LoRA adapter, runs one real forward+backward step, then adds a second adapter and hot-swaps. Fully wrapped — any failure is *recorded*, never crashes the session. Rerun after §4 has freed the models; on a tight T4 you can restart the runtime, rerun §0–§2 + §5a–§7 from checkpoints, then this cell.

In [12]:
#@title §8b · QLoRA + multi-adapter on the frozen GLM checkpoint
qlora_report, multilora_report = {}, {}
try:
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
    torch.cuda.reset_peak_memory_stats()
    tok_g, model = load_model(FROZEN["candidate"]["model_id"])
    model = prepare_model_for_kbit_training(model)
    linear = sorted({n.split(".")[-1] for n, m in model.named_modules()
                     if m.__class__.__name__.endswith("Linear4bit")})
    pmodel = get_peft_model(model, LoraConfig(r=16, lora_alpha=32, lora_dropout=0.05,
                            target_modules=linear, task_type="CAUSAL_LM"))
    batch = tok_g(["Translate to Cantonese: How are you? 你好嘛？"],
                  return_tensors="pt").to(pmodel.device)
    out = pmodel(**batch, labels=batch["input_ids"]); out.loss.backward()
    qlora_report = {"status": "PASS", "target_modules": linear,
        "trainable_params": int(sum(p.numel() for p in pmodel.parameters() if p.requires_grad)),
        "one_step_loss": round(float(out.loss), 4),
        "peak_vram_gb": round(torch.cuda.max_memory_allocated()/1e9, 2)}
    pmodel.add_adapter("yue_dialect", LoraConfig(r=8, lora_alpha=16,
                       target_modules=linear, task_type="CAUSAL_LM"))
    pmodel.set_adapter("yue_dialect"); pmodel.set_adapter("default")
    multilora_report = {"status": "PASS",
        "adapters_loaded": list(pmodel.peft_config.keys()),
        "hot_swap": "default -> yue_dialect -> default OK",
        "serving_plan": "one GLM base + per-dialect LoRA adapters; verify vLLM enable_lora on the deployment GPU"}
    del pmodel, model, tok_g
except Exception as e:
    err = {"status": "FAIL", "error": f"{type(e).__name__}: {str(e)[:200]}"}
    qlora_report = qlora_report or err
    multilora_report = multilora_report or err
free_vram()
compat_report = {"tokenizer": tok_report, "qlora": qlora_report, "multi_lora": multilora_report}
json.dump(compat_report, open("outputs/compatibility.json","w"), indent=2, ensure_ascii=False)
print(json.dumps({"qlora": qlora_report, "multi_lora": multilora_report}, indent=2, ensure_ascii=False))

Loading weights:   0%|          | 0/523 [00:00<?, ?it/s]

/tmp/ipykernel_834/2730832430.py:17: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  "one_step_loss": round(float(out.loss), 4),

VRAM in use: 4.64 GB
{
  "qlora": {
    "status": "PASS",
    "target_modules": [
      "down_proj",
      "gate_up_proj",
      "k_proj",
      "o_proj",
      "q_proj",
      "v_proj"
    ],
    "trainable_params": 47595520,
    "one_step_loss": 3.9233,
    "peak_vram_gb": 10.43
  },
  "multi_lora": {
    "status": "PASS",
    "adapters_loaded": [
      "default",
      "yue_dialect"
    ],
    "hot_swap": "default -> yue_dialect -> default OK",
    "serving_plan": "one GLM base + per-dialect LoRA adapters; verify vLLM enable_lora on the deployment GPU"
  }
}

## §9 · Decision record *(criterion 5)*

Pre-registered thresholds, auto-scored. Quality checks use **COMET-22 when available, chrF otherwise**; human criteria stay PENDING until §7b has filled reviews.

| # | Criterion | Threshold |
|---|---|---|
| 1 | eng→yue quality (COMET or chrF): GLM vs baseline | ≥ baseline − 1% |
| 2 | eng→yue % genuine Cantonese (auto screen) | ≥ baseline |
| 3 | eng→yue human authenticity mean | ≥ baseline AND ≥ 3.5 |
| 4 | eng→cmn quality: GLM vs baseline | ≥ baseline − 1% |
| 5 | eng→cmn human adequacy+fluency mean | ≥ baseline − 0.25 |
| 6 | QLoRA smoke test | PASS, VRAM fits target GPU |
| 7 | GLM Cantonese tokenizer fertility | ≤ 1.15 × baseline |
| 8 | Multi-LoRA adapters | PASS |

Mapping: all pass → **REPLACE** · one language side passes, the other fails → **ADOPT ALONGSIDE**, route by direction · 6–8 fail or quality clearly worse → **RULE OUT**.

In [13]:
#@title §9 · Auto-score thresholds + write docs/DECISION.md
QCOL = "COMET-22" if "COMET-22" in score_df.columns else "chrF"

def metric(tag, d):
    return float(score_df[(score_df.model == tag) & (score_df.direction == d)][QCOL].iloc[0])

def qual(tag):
    return float(qual_df[qual_df.model == tag]["% genuine Cantonese"].iloc[0])

hs = human_summary if "human_summary" in dir() and human_summary else {}
def human_ok(short, cols, fn):
    d = hs.get(short, {})
    if not d or d.get("n_scored", 0) == 0:
        return None, "PENDING"
    g, q = d["mean_scores"].get("glm", {}), d["mean_scores"].get("qwen", {})
    try:
        gv = sum(g[c] for c in cols)/len(cols); qv = sum(q[c] for c in cols)/len(cols)
    except KeyError:
        return None, "PENDING"
    return fn(gv, qv), f"glm={gv:.2f} qwen={qv:.2f} (n={d['n_scored']})"

tol = lambda q: 0.01*abs(q)                     # "within 1% of baseline"
checks = {}
gy, qy = metric("glm","eng_Latn->yue_Hant"), metric("qwen","eng_Latn->yue_Hant")
gc_, qc = metric("glm","eng_Latn->zho_Hans"), metric("qwen","eng_Latn->zho_Hans")
checks[1] = (gy >= qy - tol(qy), f"{QCOL} yue: glm={gy} qwen={qy}")
checks[2] = (qual("glm") >= qual("qwen"), f"%canto glm={qual('glm')} qwen={qual('qwen')}")
checks[3] = human_ok("eng_yue", ["authenticity_1to5"], lambda g,q: g >= q and g >= 3.5)
checks[4] = (gc_ >= qc - tol(qc), f"{QCOL} cmn: glm={gc_} qwen={qc}")
checks[5] = human_ok("eng_cmn", ["adequacy_1to5","fluency_1to5"], lambda g,q: g >= q - 0.25)
checks[6] = (compat_report["qlora"].get("status") == "PASS",
             f"{compat_report['qlora'].get('peak_vram_gb','?')} GB peak" if compat_report["qlora"].get("status")=="PASS"
             else compat_report["qlora"].get("error","")[:80])
checks[7] = (tok_report["glm"]["fertility_yue"] <= 1.15*tok_report["qwen"]["fertility_yue"],
             f"fert glm={tok_report['glm']['fertility_yue']} qwen={tok_report['qwen']['fertility_yue']}")
checks[8] = (compat_report["multi_lora"].get("status") == "PASS", "adapter hot-swap")

yue = [checks[1][0], checks[2][0]] + ([checks[3][0]] if checks[3][0] is not None else [])
cmn = [checks[4][0]] + ([checks[5][0]] if checks[5][0] is not None else [])
infra = [checks[6][0], checks[7][0], checks[8][0]]
pending = checks[3][0] is None or checks[5][0] is None

if not all(infra):
    rec = "RULE OUT (pipeline-fit failure)"
elif all(yue) and all(cmn):
    rec = "REPLACE baseline with GLM" + (" (provisional — human review pending)" if pending else "")
elif all(yue) or all(cmn):
    rec = ("ADOPT ALONGSIDE — route " + ("eng→yue" if all(yue) else "eng→cmn") + " to GLM"
           + (" (provisional — human review pending)" if pending else ""))
else:
    rec = "RULE OUT (no quality advantage)"

parts = ["# GLM adoption decision — Sprint 48 evidence record",
         f"Config: configs/baseline.json v{FROZEN['config_version']} | fingerprint {FP}",
         "Supersedes: Sprint 47 exploration (5 inconsistent evals)",
         f"Quality metric used: {QCOL}", "",
         f"## RECOMMENDATION: {rec}",
         "Sign-off: ______   Date: ______", "", "## Threshold scorecard"]
for i in sorted(checks):
    ok, detail = checks[i]
    parts.append(f"- [{'PENDING' if ok is None else ('PASS' if ok else 'FAIL')}] #{i}: {detail}")
parts += ["", "## Automatic metrics (FLORES-200 devtest)", score_df.to_string(index=False),
          "", "## Cantonese authenticity screen", qual_df.to_string(index=False),
          "", "## Human review", json.dumps(hs, indent=2) if hs else "PENDING — see human_review/",
          "", "## Pipeline compatibility", json.dumps(compat_report, indent=2, ensure_ascii=False)[:3000],
          "", "## Caveats",
          "- FLORES yue_Hant references skew formal Standard Written Chinese; the human authenticity review is authoritative for colloquial Cantonese.",
          f"- Run used N_SENTENCES={len(flores['yue_Hant'])}" +
          (" — set 1012 (full devtest) before final sign-off." if len(flores["yue_Hant"]) < 1012 else " (full devtest)."),
          "- Sprint 47 baseline outputs were right-padded (corrupted batching); this run regenerated both systems left-padded under the frozen config.",
          "- Valid ONLY for the pinned checkpoint + quantization; any change = new config version + full rerun."]
doc = "\n".join(parts)
open("docs/DECISION.md","w").write(doc)
print(doc[:2400])

# GLM adoption decision — Sprint 48 evidence record
Config: configs/baseline.json v1.0.0 | fingerprint 7f05cd7dba78
Supersedes: Sprint 47 exploration (5 inconsistent evals)
Quality metric used: chrF

## RECOMMENDATION: REPLACE baseline with GLM (provisional — human review pending)
Sign-off: ______   Date: ______

## Threshold scorecard
- [PASS] #1: chrF yue: glm=21.22 qwen=14.71
- [PASS] #2: %canto glm=93.5 qwen=81.5
- [PENDING] #3: PENDING
- [PASS] #4: chrF cmn: glm=37.02 qwen=35.53
- [PENDING] #5: PENDING
- [PASS] #6: 10.43 GB peak
- [PASS] #7: fert glm=1.5 qwen=1.385
- [PASS] #8: adapter hot-swap

## Automatic metrics (FLORES-200 devtest)
model          direction  chrF
  glm eng_Latn->yue_Hant 21.22
  glm eng_Latn->zho_Hans 37.02
  glm yue_Hant->eng_Latn 57.13
  glm zho_Hans->eng_Latn 58.23
 qwen eng_Latn->yue_Hant 14.71
 qwen eng_Latn->zho_Hans 35.53
 qwen yue_Hant->eng_Latn 57.09
 qwen zho_Hans->eng_Latn 57.61

## Cantonese authenticity screen
model  % genuine Cantonese  % Mandarin-in-Trad  % mixed  % neutral
  glm                 93.5                 0.5      0.5        5.5
 qwen                 81.5                 1.5      3.0       14.0

## Human review
{
  "eng_yue": {
    "n_scored": 0,
    "preferences": {
      "glm": 0,
      "qwen": 0,
      "tie": 0
    },
    "mean_scores": {}
  },
  "eng_cmn": {
    "n_scored": 0,
    "preferences": {
      "glm": 0,
      "qwen": 0,
      "tie": 0
    },
    "mean_scores": {}
  }
}

## Pipeline compatibility
{
  "tokenizer": {
    "glm": {
      "model": "zai-org/GLM-4-9B-0414",
      "fertility_yue": 1.5,
      "fertility_cmn": 0.614,
      "yue_vs_cmn_ratio": 2.443,
      "multi_token_particles": {
        "嘅": 2,
        "喺": 2,
        "咗": 2,
        "冇": 2,
        "啲": 2,
        "嗰": 2,
        "咁": 2,
        "哋": 2,
        "嚟": 2,
        "俾": 2,
        "睇": 2,
        "諗": 2,
        "搵": 2,
        "㗎": 3,
        "喎": 2,
        "囉": 2,
        "啫": 2,
        "嘞": 2,
        "咩": 2
      }
    },
    "qwen": {
      "model": "Qwen/Qwen2.5-7B-Instruct",
      "fertility_yue": 1.385,
      "fertility_cmn": 0.643,
      "yue_vs_cmn_ratio": 2.154,
      "multi_token_particles": {
        "嘅": 2,
        "喺": 2,
        "咗": 2,
        "冇": 2,
        "啲": 2,
        "嗰": 2,
        "咁": 2,
        "哋": 2,
        "嚟": 2,
        "諗": 2,
        "搵": 2,
        "㗎": 3,
        "喎": 2,
        "囉

## §10 · Push notebook + results to the shared pod repo *(criterion 6)*

Save this notebook into `/content` first (File → Download → .ipynb, then drag into the Files panel) so it gets committed. The unblinding key is excluded.

In [14]:
#@title §10 · Commit + push to the pod repo
GH_USER = "srinayani123"                          #@param {type:"string"}
GH_REPO = "vosyn--supernova--project_sprint47"    #@param {type:"string"}

from google.colab import userdata
import subprocess, shutil, glob

work = "/content/_push"

def git(*args, check=True):
    r = subprocess.run(["git", "-C", work, *args], capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.returncode and r.stderr.strip(): print("STDERR:", r.stderr.strip()[:300])
    if check and r.returncode:
        raise RuntimeError(f"git {' '.join(args)} failed (exit {r.returncode})")
    return r

token = userdata.get("GITHUB_TOKEN")
assert token, "No GITHUB_TOKEN secret — add it via the key panel on the left."
repo_url = f"https://{GH_USER}:{token}@github.com/{GH_USER}/{GH_REPO}.git"

shutil.rmtree(work, ignore_errors=True)
clone = subprocess.run(["git", "clone", repo_url, work], capture_output=True, text=True)
if clone.returncode:
    print("Clone failed (empty repo?) — initializing fresh.")
    subprocess.run(["git", "init", work], check=True)
    git("remote", "add", "origin", repo_url)

for d in ("outputs", "configs", "docs", "human_review"):
    if os.path.isdir(d):
        shutil.copytree(d, f"{work}/{d}", dirs_exist_ok=True)
for pat in ("/content/*.ipynb", "/content/*.md"):
    for f in glob.glob(pat):
        shutil.copy(f, work)
open(f"{work}/.gitignore", "w").write("human_review/UNBLIND_KEY_DO_NOT_OPEN.json\n")
kp = f"{work}/human_review/UNBLIND_KEY_DO_NOT_OPEN.json"
if os.path.exists(kp):
    os.remove(kp)
subprocess.run(["git", "-C", work, "rm", "--cached", "-q",
                "human_review/UNBLIND_KEY_DO_NOT_OPEN.json"], capture_output=True)

git("config", "user.email", f"{GH_USER}@users.noreply.github.com")
git("config", "user.name", GH_USER)
git("checkout", "-B", "main")
git("add", "-A")
commit = git("commit", "-m",
             "Sprint 48 v3: standardized GLM eval vs frozen baseline (no-restart env, chrF primary, resumable) + human review + pipeline fit + decision",
             check=False)
if "nothing to commit" in (commit.stdout + commit.stderr):
    print("Nothing new to commit.")
git("push", "-u", "origin", "main")
print(f"\nDone — share with the team: https://github.com/{GH_USER}/{GH_REPO}")

M	outputs/cantonese_authenticity.csv
M	outputs/glm_eng_Latn_yue_Hant.json
M	outputs/glm_eng_Latn_zho_Hans.json
M	outputs/glm_yue_Hant_eng_Latn.json
M	outputs/glm_zho_Hans_eng_Latn.json
M	outputs/qwen_eng_Latn_yue_Hant.json
M	outputs/qwen_eng_Latn_zho_Hans.json
M	outputs/qwen_yue_Hant_eng_Latn.json
M	outputs/qwen_zho_Hans_eng_Latn.json
M	outputs/scores.csv
Your branch is up to date with 'origin/main'.
[main 4898cdd] Sprint 48 v3: standardized GLM eval vs frozen baseline (no-restart env, chrF primary, resumable) + human review + pipeline fit + decision
 18 files changed, 540 insertions(+), 4876 deletions(-)
 create mode 100644 .gitignore
 create mode 100644 configs/baseline.json
 create mode 100644 configs/environment.txt
 create mode 100644 docs/DECISION.md
 create mode 100644 human_review/human_review_summary.json
 create mode 100644 human_review/review_eng_cmn.csv
 create mode 100644 human_review/review_eng_yue.csv
 create mode 100644 outputs/compatibility.json
 rewrite outputs/glm_eng_Latn_yue_Hant.json (99%)
 rewrite outputs/glm_eng_Latn_zho_Hans.json (98%)
 rewrite outputs/glm_yue_Hant_eng_Latn.json (98%)
 rewrite outputs/glm_zho_Hans_eng_Latn.json (98%)
 rewrite outputs/qwen_eng_Latn_yue_Hant.json (99%)
 rewrite outputs/qwen_eng_Latn_zho_Hans.json (98%)
 rewrite outputs/qwen_yue_Hant_eng_Latn.json (98%)
 rewrite outputs/qwen_zho_Hans_eng_Latn.json (98%)
Branch 'main' set up to track remote branch 'main' from 'origin'.

Done — share with the team: https://github.com/srinayani123/vosyn--supernova--project_sprint47