# GLM Cantonese Evaluation — FLORES-200 Zero-Shot Translation

**Goal:** Decide whether a GLM-family model (GLM-4-9B-Chat / GLM-4-9B-0414) should be **adopted alongside Qwen2.5**, **replace Qwen2.5**, or be **ruled out** for Cantonese work.

**What this notebook does:**
1. Zero-shot translation on FLORES-200 devtest across four directions:
   - `eng_Latn → yue_Hant` (English → Cantonese)
   - `eng_Latn → zho_Hans` (English → Mandarin)
   - `yue_Hant → eng_Latn` (Cantonese → English)
   - `zho_Hans → eng_Latn` (Mandarin → English)
2. Scores with **COMET-22** (`Unbabel/wmt22-comet-da`) and **chrF** (sacreBLEU chrF2).
3. Qualitative check: does the model output **genuine Cantonese** (嘅/咗/喺/唔/佢/哋…) or **Mandarin dressed in Traditional characters** (的/了/在/不/他/們…)?
4. Optional side-by-side baseline: **Qwen2.5-7B-Instruct**.
5. Push results + notebook to a GitHub repo.

**Runtime:** any Colab GPU works. Defaults are tuned for the free-tier **T4** (4-bit NF4 quantization, fp16 compute, batch size 4). On an A100 you can set `LOAD_IN_4BIT = False` and `BATCH_SIZE = 16` for a faster, full-precision run.

In [1]:
import os
os.environ["USE_TF"] = "0"

In [2]:
#@title 1. Install dependencies (auto-restarts runtime once — just re-run this cell after)
import os

if not os.path.exists("/content/_deps_ok"):
    # NOTE: do NOT `-U pandas` here. unbabel-comet's dependency chain downgrades
    # numpy to 1.26.x, and any pandas>=3 wheel is compiled against numpy 2 ->
    # "numpy.dtype size changed" binary incompatibility. We pin a consistent pair.
    !pip install -q -U transformers accelerate sentencepiece tiktoken
    !pip install -q -U datasets sacrebleu "unbabel-comet>=2.2.0" bitsandbytes
    !pip install -q "numpy==1.26.4" "pandas==2.2.2"
    open("/content/_deps_ok", "w").write("ok")
    print("\nInstalled. Restarting the runtime to load the pinned numpy cleanly…")
    print("After the restart, RE-RUN THIS CELL (it will skip installs) and continue.")
    os.kill(os.getpid(), 9)   # hard restart; expected — not an error

import torch, pandas as pd, numpy as np
print("numpy", np.__version__, "| pandas", pd.__version__, "| torch", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

numpy 1.26.4 | pandas 2.2.2 | torch 2.11.0+cu128
CUDA available: True
GPU: NVIDIA A100-SXM4-40GB

In [3]:
#@title 2. Configuration
# ---- Models under evaluation ----
# GLM options (pick one, or run the notebook twice):
#   "zai-org/glm-4-9b-chat"      -> GLM-4 (June 2024), 26-language chat model
#   "zai-org/GLM-4-9B-0414"      -> GLM-4-0414 (2025), optimized for batch tasks incl. translation
GLM_MODEL_ID   = "zai-org/GLM-4-9B-0414"
QWEN_MODEL_ID  = "Qwen/Qwen2.5-7B-Instruct"   # baseline; set RUN_QWEN_BASELINE=False to skip
RUN_QWEN_BASELINE = True

LOAD_IN_4BIT = True         # True fits 9B models on free-tier T4/L4 (~5.5 GB weights).
                            # Only set False if you have an A100/H100 (>=40 GB).
BATCH_SIZE = 4              # generation batch size; raise to 8-16 on A100
MAX_NEW_TOKENS = 256
N_SENTENCES = 200           # FLORES devtest has 1012; 200 keeps Colab runtime manageable.
                            # Set to None to run the full devtest set.

LANGS = {
    "eng_Latn": "English",
    "yue_Hant": "Cantonese (written vernacular Cantonese, 粵語白話文, Traditional characters)",
    "zho_Hans": "Mandarin Chinese (Simplified characters)",
}

DIRECTIONS = [
    ("eng_Latn", "yue_Hant"),   # English -> Cantonese
    ("eng_Latn", "zho_Hans"),   # English -> Mandarin
    ("yue_Hant", "eng_Latn"),   # Cantonese -> English
    ("zho_Hans", "eng_Latn"),   # Mandarin -> English
]

SEED = 42

## 3. Load FLORES-200 devtest

Primary source is `facebook/flores`; if that fails (it is gated/remote-code in some environments), we fall back to the `Muennighoff/flores200` mirror.

In [4]:
#@title 3. Load FLORES-200 devtest sentences (direct download, no HF auth needed)
import os, tarfile

FLORES_URL = "https://dl.fbaipublicfiles.com/nllb/flores200_dataset.tar.gz"
FLORES_DIR = "/content/flores200_dataset"

if not os.path.exists(FLORES_DIR):
    print("Downloading FLORES-200 (~25 MB)…")
    !wget -q -O /content/flores200.tar.gz {FLORES_URL}
    with tarfile.open("/content/flores200.tar.gz") as tf:
        tf.extractall("/content")
    print("Extracted.")

def load_flores_devtest(lang_code):
    path = f"{FLORES_DIR}/devtest/{lang_code}.devtest"
    with open(path, encoding="utf-8") as f:
        return [line.rstrip("\n") for line in f]

flores = {code: load_flores_devtest(code) for code in LANGS}
n_total = len(flores["yue_Hant"])
assert all(len(v) == n_total for v in flores.values()), "FLORES splits misaligned!"

if N_SENTENCES:
    flores = {k: v[:N_SENTENCES] for k, v in flores.items()}
print(f"Loaded {len(flores['yue_Hant'])} parallel sentences per language.")
for k in flores:
    print(f"  {k}: {flores[k][0][:80]}…")

Loaded 200 parallel sentences per language.
  eng_Latn: "We now have 4-month-old mice that are non-diabetic that used to be diabetic," h…
  yue_Hant: 他補充說：「我們現在有 4 個月大的老鼠，牠們現在沒有糖尿病，但過去曾患糖尿病。」…
  zho_Hans: 他补充道：“我们现在有 4 个月大没有糖尿病的老鼠，但它们曾经得过该病。”…

In [5]:
#@title 4. Model loading + zero-shot generation helpers
import torch, gc
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

# T4 GPUs (compute capability 7.5) don't support bfloat16 — fall back to float16.
DTYPE = torch.bfloat16 if (torch.cuda.is_available()
                           and torch.cuda.is_bf16_supported()) else torch.float16
print("Using compute dtype:", DTYPE)

def load_model(model_id):
    tok = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    kwargs = dict(trust_remote_code=True, device_map="auto")
    if LOAD_IN_4BIT:
        kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=DTYPE)
    else:
        kwargs["torch_dtype"] = DTYPE
    model = AutoModelForCausalLM.from_pretrained(model_id, **kwargs).eval()
    return tok, model

def free_model(model):
    del model; gc.collect(); torch.cuda.empty_cache()

def make_prompt(src_code, tgt_code, text):
    src_name, tgt_name = LANGS[src_code], LANGS[tgt_code]
    instr = (f"Translate the following {src_name} sentence into {tgt_name}. "
             f"Output ONLY the translation, with no explanation, no romanization, "
             f"and no quotation marks.")
    if tgt_code == "yue_Hant":
        instr += (" The translation must be natural written vernacular Cantonese "
                  "as used in Hong Kong (using words like 嘅、喺、唔、佢 where natural), "
                  "NOT Standard Written Chinese.")
    return f"{instr}\n\n{src_name}: {text}\n{tgt_name}:"

@torch.no_grad()
def translate_batch(tok, model, prompts, batch_size=None):
    batch_size = batch_size or BATCH_SIZE
    outs = []
    for i in range(0, len(prompts), batch_size):
        chunk = prompts[i:i+batch_size]
        msgs = [[{"role": "user", "content": p}] for p in chunk]
        enc = tok.apply_chat_template(
            msgs, add_generation_prompt=True, tokenize=True,
            return_tensors="pt", return_dict=True, padding=True).to(model.device)
        gen = model.generate(
            **enc, max_new_tokens=MAX_NEW_TOKENS, do_sample=False,
            temperature=None, top_p=None,
            pad_token_id=tok.pad_token_id or tok.eos_token_id)
        for j, out_ids in enumerate(gen):
            new_ids = out_ids[enc["input_ids"].shape[1]:]
            txt = tok.decode(new_ids, skip_special_tokens=True).strip()
            outs.append(txt.split("\n")[0].strip().strip('"“”'))
        if (i // batch_size) % 5 == 0:
            print(f"  {min(i+batch_size, len(prompts))}/{len(prompts)}")
    return outs

Using compute dtype: torch.bfloat16

In [ ]:
!pip install -q "protobuf==5.29.5"
import os
os.kill(os.getpid(), 9)   # restart so the new protobuf loads cleanly

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.9/319.9 kB 22.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unbabel-comet 2.2.7 requires protobuf<5.0.0,>=4.24.4, but you have protobuf 5.29.5 which is incompatible.

In [6]:
#@title 5. Run zero-shot translation for all four directions
import json, os
os.makedirs("outputs", exist_ok=True)

def run_model(model_id, tag):
    print(f"\n===== Loading {model_id} =====")
    tok, model = load_model(model_id)
    results = {}
    for src, tgt in DIRECTIONS:
        d = f"{src}->{tgt}"
        print(f"\n--- {tag}: {d} ---")
        prompts = [make_prompt(src, tgt, s) for s in flores[src]]
        hyps = translate_batch(tok, model, prompts)
        results[d] = {"src": flores[src], "ref": flores[tgt], "hyp": hyps}
        with open(f"outputs/{tag}_{src}_{tgt}.json", "w") as f:
            json.dump(results[d], f, ensure_ascii=False, indent=1)
    free_model(model)
    return results

all_results = {}
all_results["glm"] = run_model(GLM_MODEL_ID, "glm")
if RUN_QWEN_BASELINE:
    all_results["qwen"] = run_model(QWEN_MODEL_ID, "qwen")

===== Loading zai-org/GLM-4-9B-0414 =====

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.90G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.90G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/4.03G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

--- glm: eng_Latn->yue_Hant ---
  4/200
  24/200
  44/200
  64/200
  84/200
  104/200
  124/200
  144/200
  164/200
  184/200

--- glm: eng_Latn->zho_Hans ---
  4/200
  24/200
  44/200
  64/200
  84/200
  104/200
  124/200
  144/200
  164/200
  184/200

--- glm: yue_Hant->eng_Latn ---
  4/200
  24/200
  44/200
  64/200
  84/200
  104/200
  124/200
  144/200
  164/200
  184/200

--- glm: zho_Hans->eng_Latn ---
  4/200
  24/200
  44/200
  64/200
  84/200
  104/200
  124/200
  144/200
  164/200
  184/200

===== Loading Qwen/Qwen2.5-7B-Instruct =====

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/3.56G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/3.95G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

The following generation flags are not valid and may be ignored: ['top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

--- qwen: eng_Latn->yue_Hant ---

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  4/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  24/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  44/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  64/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  84/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  104/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  124/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  144/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  164/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  184/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

--- qwen: eng_Latn->zho_Hans ---

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  4/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  24/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  44/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  64/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  84/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  104/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  124/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  144/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  164/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  184/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

--- qwen: yue_Hant->eng_Latn ---

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  4/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  24/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  44/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  64/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  84/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  104/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  124/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  144/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  164/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  184/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

--- qwen: zho_Hans->eng_Latn ---

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  4/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  24/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  44/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  64/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  84/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  104/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  124/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  144/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  164/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

  184/200

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

In [7]:
#@title 6. Score with chrF and COMET-22
import sacrebleu
from comet import download_model, load_from_checkpoint

comet_path = download_model("Unbabel/wmt22-comet-da")
comet_model = load_from_checkpoint(comet_path)

def score_direction(res):
    chrf = sacrebleu.corpus_chrf(res["hyp"], [res["ref"]]).score
    comet_data = [{"src": s, "mt": h, "ref": r}
                  for s, h, r in zip(res["src"], res["hyp"], res["ref"])]
    comet = comet_model.predict(comet_data, batch_size=8,
                                gpus=1 if torch.cuda.is_available() else 0)
    return chrf, comet.system_score, comet.scores

rows = []
seg_scores = {}
for tag, results in all_results.items():
    for d, res in results.items():
        chrf, comet_sys, comet_segs = score_direction(res)
        seg_scores[(tag, d)] = comet_segs
        rows.append({"model": tag, "direction": d,
                     "chrF": round(chrf, 2), "COMET-22": round(comet_sys, 4)})
        print(f"{tag:5s} {d:22s} chrF={chrf:.2f}  COMET-22={comet_sys:.4f}")

score_df = pd.DataFrame(rows)
score_df.to_csv("outputs/scores.csv", index=False)
score_df

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

hparams.yaml:   0%|          | 0.00/567 [00:00<?, ?B/s]

LICENSE: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

checkpoints/model.ckpt:   0%|          | 0.00/2.32G [00:00<?, ?B/s]

INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.8.3.post1 to v2.6.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../root/.cache/huggingface/hub/models--Unbabel--wmt22-comet-da/snapshots/2760a223ac957f30acfb18c8aa649b01cf1d75f2/checkpoints/model.ckpt`

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/core/saving.py:197: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.utilities.rank_zero:You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 25/25 [00:01<00:00, 14.31it/s]
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

glm   eng_Latn->yue_Hant     chrF=21.14  COMET-22=0.7917

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 25/25 [00:01<00:00, 15.85it/s]
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

glm   eng_Latn->zho_Hans     chrF=36.80  COMET-22=0.8752

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 25/25 [00:01<00:00, 15.74it/s]
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

glm   yue_Hant->eng_Latn     chrF=57.25  COMET-22=0.8630

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 25/25 [00:01<00:00, 15.90it/s]
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

glm   zho_Hans->eng_Latn     chrF=58.53  COMET-22=0.8703

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 25/25 [00:01<00:00, 13.70it/s]
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

qwen  eng_Latn->yue_Hant     chrF=13.13  COMET-22=0.6747

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 25/25 [00:01<00:00, 15.47it/s]
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

qwen  eng_Latn->zho_Hans     chrF=32.47  COMET-22=0.8327

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 25/25 [00:01<00:00, 15.79it/s]
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

qwen  yue_Hant->eng_Latn     chrF=54.32  COMET-22=0.8365

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 25/25 [00:01<00:00, 15.57it/s]

qwen  zho_Hans->eng_Latn     chrF=54.03  COMET-22=0.8368

  model           direction   chrF  COMET-22
0   glm  eng_Latn->yue_Hant  21.14    0.7917
1   glm  eng_Latn->zho_Hans  36.80    0.8752
2   glm  yue_Hant->eng_Latn  57.25    0.8630
3   glm  zho_Hans->eng_Latn  58.53    0.8703
4  qwen  eng_Latn->yue_Hant  13.13    0.6747
5  qwen  eng_Latn->zho_Hans  32.47    0.8327
6  qwen  yue_Hant->eng_Latn  54.32    0.8365
7  qwen  zho_Hans->eng_Latn  54.03    0.8368

## 7. Qualitative check — genuine Cantonese vs. Mandarin in Traditional script

A model can score decently on chrF/COMET while actually emitting **Standard Written Chinese (Mandarin grammar) rendered in Traditional characters**. We detect this by comparing densities of:

- **Cantonese-distinctive markers:** 嘅 咗 喺 哋 嗰 啲 嘢 冇 唔 睇 諗 畀 攞 咁 乜 邊 嚟 緊 埋 晒 囉 㗎 啩 喎 咩 呢. These include the possessive/nominalizer 嘅 (vs 的), perfective 咗 (vs 了), locative 喺 (vs 在), negators 唔/冇 (vs 不/沒), and sentence-final particles.
- **Mandarin-distinctive markers:** 的 了 在 不 沒 他 她 它 們 是 這 那 說 看 給 甚麼 什麼 怎麼 呢些.

The check runs on the one direction that targets Cantonese (`eng_Latn -> yue_Hant`). A useful side-by-side: compare the model's eng->yue output register against its eng->zho_Hans output — if they read the same apart from the script, the model is not producing Cantonese. Each hypothesis is classified as `cantonese`, `mandarin-like`, `mixed`, or `neutral`.

In [8]:
#@title 7. Cantonese authenticity analysis
import re

CANTO_MARKERS = set("嘅咗喺哋嗰啲嘢冇唔諗畀攞咁乜嚟緊晒囉㗎啩喎咩")
CANTO_BIGRAMS = ["點解", "而家", "琴日", "聽日", "咩嘢", "邊個", "邊度", "得閒",
                 "鍾意", "好似", "唔係", "係咪", "冇得", "俾佢", "睇吓", "諗吓"]
MANDO_MARKERS = set("的了在不沒他她它們這那说說給")
MANDO_BIGRAMS = ["什麼", "甚麼", "怎麼", "為什麼", "喜歡", "現在", "昨天", "明天",
                 "知道", "沒有", "是的", "可以", "他們", "她們"]

def han_len(t):
    return max(1, len(re.findall(r"[\u4e00-\u9fff\u3400-\u4dbf]", t)))

def canto_score(text):
    n = han_len(text)
    c = sum(text.count(ch) for ch in CANTO_MARKERS) + \
        2 * sum(text.count(bg) for bg in CANTO_BIGRAMS)
    m = sum(text.count(ch) for ch in MANDO_MARKERS) + \
        2 * sum(text.count(bg) for bg in MANDO_BIGRAMS)
    return c / n, m / n

def classify(text, c_thresh=0.03, m_thresh=0.05):
    c, m = canto_score(text)
    if c >= c_thresh and c > m * 0.5: return "cantonese"
    if m >= m_thresh and c < c_thresh: return "mandarin-like"
    if c > 0 and m > 0:               return "mixed"
    return "neutral"

qual_rows = []
for tag, results in all_results.items():
    for d, res in results.items():
        if not d.endswith("yue_Hant"):
            continue
        labels = [classify(h) for h in res["hyp"]]
        ref_labels = [classify(r) for r in res["ref"]]
        n = len(labels)
        qual_rows.append({
            "model": tag, "direction": d,
            "% genuine Cantonese": round(100*labels.count("cantonese")/n, 1),
            "% Mandarin-in-Trad": round(100*labels.count("mandarin-like")/n, 1),
            "% mixed": round(100*labels.count("mixed")/n, 1),
            "% neutral": round(100*labels.count("neutral")/n, 1),
            "(ref % Cantonese)": round(100*ref_labels.count("cantonese")/n, 1),
        })
qual_df = pd.DataFrame(qual_rows)
qual_df.to_csv("outputs/cantonese_authenticity.csv", index=False)
qual_df

,model,direction,% genuine Cantonese,% Mandarin-in-Trad,% mixed,% neutral,(ref % Cantonese)
0,glm,eng_Latn->yue_Hant,93.5,0.5,0.5,5.5,0.0
1,qwen,eng_Latn->yue_Hant,82.0,3.0,4.0,11.0,0.0

In [9]:
#@title 7b. Inspect concrete examples (worst offenders + best outputs)
def show_examples(tag, d, k=5):
    res = all_results[tag][d]
    print(f"\n########## {tag} — {d} ##########")
    mand = [(s, h, r) for s, h, r in zip(res["src"], res["hyp"], res["ref"])
            if classify(h) == "mandarin-like"]
    good = [(s, h, r) for s, h, r in zip(res["src"], res["hyp"], res["ref"])
            if classify(h) == "cantonese"]
    print(f"\n--- Mandarin-in-Traditional-script outputs ({len(mand)} total) ---")
    for s, h, r in mand[:k]:
        print(f"SRC: {s}\nHYP: {h}\nREF: {r}\n")
    print(f"--- Genuine Cantonese outputs ({len(good)} total) ---")
    for s, h, r in good[:k]:
        print(f"SRC: {s}\nHYP: {h}\nREF: {r}\n")

for tag in all_results:
    show_examples(tag, "eng_Latn->yue_Hant")

########## glm — eng_Latn->yue_Hant ##########

--- Mandarin-in-Traditional-script outputs (1 total) ---
SRC: This will allow it to be backwards compatible with 802.11a, 802.11b and 802.11g, provided that the base station has dual radios.
HYP: 呢樣會令佢可以同 802.11a, 802.11b 同 802.11g 兼容，但係要基地台有雙無線電先得。
REF: 這將允許它兼容舊款的 802.11a、802.11b 和802.11g，前提是基站有雙無線電。

--- Genuine Cantonese outputs (187 total) ---
SRC: "We now have 4-month-old mice that are non-diabetic that used to be diabetic," he added.
HYP: 我哋而家得返四個月大嘅老鼠，佢哋係冇糖尿病嘅，不過之前係有糖尿病嘅，佢加咗。
REF: 他補充說：「我們現在有 4 個月大的老鼠，牠們現在沒有糖尿病，但過去曾患糖尿病。」

SRC: Like some other experts, he is skeptical about whether diabetes can be cured, noting that these findings have no relevance to people who already have Type 1 diabetes.
HYP: 佢同啲其他專家一樣，對糖尿病可唔可以醫好嘅問題都好懷疑，並且指出呢啲發現對已經有第一型糖尿病嘅人冇關係。
REF: 和其他專家一樣，他對能否治愈​​糖尿病抱懷疑態度，並指出該等發現與1型糖尿病患者並不相關。

SRC: On Monday, Sara Danius, permanent secretary of the Nobel Committee for Literature at the Swedish Academy, publicly announced during a radio program on Sveriges Radio in Sweden the committee, unable to reach Bob Dylan directly about winning the 2016 Nobel Prize in Literature, had abandoned its efforts to reach him.
HYP: 個禮拜一，瑞典學院文學獎委員會常任秘書Sara Danius喺瑞典Sveriges Radio嘅一個電台節目入面公開宣布，委員會無法直接同Bob Dylan溝通有關獲得2016年文學獎嘅事，所以放棄咗試圖同佢聯絡嘅嘢。
REF: 在星期一，瑞典學院諾貝爾文學獎委員會常任秘書薩拉·達尼烏斯在瑞典 Sveriges 電台的一個廣播節目中公開宣布，該委員會無法就獲得 2016 年諾貝爾文學獎一事直接聯繫鮑勃·迪倫，因此放棄聯繫他。

SRC: Danius said, "Right now we are doing nothing. I have called and sent emails to his closest collaborator and received very friendly replies. For now, that is certainly enough."
HYP: 打尼奧話，「而家我哋冇嘢做。我已經打電話同埋發電郵咗佢最親密嘅合作夥伴，仲收到好友好嘅回覆。而家先至係確定咁夠晒。」
REF: 丹尼烏斯說：「現在我們不採取任何行動。我已經打電話和發送電郵給他最緊密的合作夥伴，並得到非常友善的回覆。就目前而言，這就足夠了。」

SRC: Previously, Ring's CEO, Jamie Siminoff, remarked the company started when his doorbell wasn't audible from his shop in his garage.
HYP: 以往，Ring嘅CEO Jamie Siminoff就話，公司係喺佢個車房嘅舖面，門鈴聲唔喺佢舖度聽到先開始嘅。
REF: 此前，Ring 的行政總裁Jamie Siminoff 表示公司創立的源由是從他車庫的店中聽不到門鈴。


########## qwen — eng_Latn->yue_Hant ##########

--- Mandarin-in-Traditional-script outputs (6 total) ---
SRC: The find also grants insight into the evolution of feathers in birds.
HYP: Ünivers發現亦提供鳥類羽毛演化的見解。
REF: 此發現亦讓我們更深入了解鳥類羽毛的進化。

SRC: Police said they suspect an alleged Daesh (ISIL) militant of responsibility for the attack.
HYP: 警察講俾野，他們疑心一個涉嫌伊斯蘭國武裝份子對襲擊同埋有責任。
REF: 警方指他們懷疑是次襲擊涉嫌由戴伊什（ISIL）激進分子所造成。

SRC: Liberal criticism of the reconstruction effort has focused on the awarding of reconstruction contracts to perceived Washington insiders.
HYP: 民生自由派批评重建工作集中點在京師內定的 CONTRACT承建商身上
REF: 自由派對重建工作的批評重點，在於把重建合同授予被認為是華盛頓內部人士的做法上。

SRC: Tournament top seeds South Africa started on the right note when they had a comfortable 26 - 00 win against 5th seeded Zambia.
HYP: !*** 輸入的句子似乎有些問題，"26 - 00" 不是常見的比分格式。假设是 "26 - 0"，則翻譯為：***
REF: 比賽頭號種子南非隊開局佔優勢，以26 - 00輕鬆打敗5號種子贊比亞隊。

SRC: Candidates can send representatives to witness every part of the process. In the evening, votes are counted by volunteers under heavy supervision, following specific procedures.
HYP: 考生可以派代表見證整個過程。晚間，票數由監督緊密監察下由義工計數，依循特定程序。
REF: 候選人可以派代表見證選舉過程的每一部分。傍晚的時候，義工在嚴格的監督下，按照指定程序點票。

--- Genuine Cantonese outputs (164 total) ---
SRC: "We now have 4-month-old mice that are non-diabetic that used to be diabetic," he added.
HYP: 嗗四個月大既非糖尿病鼠隻前係糖尿病嘅，佢添。
REF: 他補充說：「我們現在有 4 個月大的老鼠，牠們現在沒有糖尿病，但過去曾患糖尿病。」

SRC: Dr. Ehud Ur, professor of medicine at Dalhousie University in Halifax, Nova Scotia and chair of the clinical and scientific division of the Canadian Diabetes Association cautioned that the research is still in its early days.
HYP: dru jeh ud 呃 肯，教授喺 邁拉荷西嘅 达路士大學medicine科，糖尿病协会临床及科学分系主席，講到呢項研究仲系啲早期日。
REF: 位於新斯科舍省哈利法克斯的達爾豪西大學醫學教授、加拿大糖尿病協會臨床與科學部門主席埃胡德·烏爾醫生警告，這項研究仍處於早期階段。

SRC: Like some other experts, he is skeptical about whether diabetes can be cured, noting that these findings have no relevance to people who already have Type 1 diabetes.
HYP: 像些专家一样，佢對糖尿病可以 curing 係點樣都系懷疑，指呢啲發現對已經有型一糖尿病嘅人冇乜關係。
REF: 和其他專家一樣，他對能否治愈​​糖尿病抱懷疑態度，並指出該等發現與1型糖尿病患者並不相關。

SRC: On Monday, Sara Danius, permanent secretary of the Nobel Committee for Literature at the Swedish Academy, publicly announced during a radio program on Sveriges Radio in Sweden the committee, unable to reach Bob Dylan directly about winning the 2016 Nobel Prize in Literature, had abandoned its efforts to reach him.
HYP: 星期一，瑞典學院文學獎評委會嘅Permanent secretary Sara Danius，在瑞典Sveriges Radio嘅.ToShortwave节目上公开宣布，因為唔能夠直接联络到Bob Dylan知佢得2016年文學獎，所以評委會已經放棄嘗試联络佢。
REF: 在星期一，瑞典學院諾貝爾文學獎委員會常任秘書薩拉·達尼烏斯在瑞典 Sveriges 電台的一個廣播節目中公開宣布，該委員會無法就獲得 2016 年諾貝爾文學獎一事直接聯繫鮑勃·迪倫，因此放棄聯繫他。

SRC: Danius said, "Right now we are doing nothing. I have called and sent emails to his closest collaborator and received very friendly replies. For now, that is certainly enough."
HYP: 丹尼斯講道，「緊.WriteByte
REF: 丹尼烏斯說：「現在我們不採取任何行動。我已經打電話和發送電郵給他最緊密的合作夥伴，並得到非常友善的回覆。就目前而言，這就足夠了。」

In [10]:
#@title 8. Decision summary
print(score_df.to_string(index=False))
print()
print(qual_df.to_string(index=False))

def decide():
    if "qwen" not in all_results:
        print("\nNo Qwen baseline run — rerun with RUN_QWEN_BASELINE=True for a decision.")
        return
    g = score_df[score_df.model == "glm"].set_index("direction")
    q = score_df[score_df.model == "qwen"].set_index("direction")
    delta = (g[["chrF", "COMET-22"]] - q[["chrF", "COMET-22"]])
    print("\nGLM minus Qwen2.5 (positive = GLM better):")
    print(delta.round(3).to_string())

    gq = qual_df[qual_df.model == "glm"]["% genuine Cantonese"].mean()
    qq = qual_df[qual_df.model == "qwen"]["% genuine Cantonese"].mean()
    print(f"\n%% genuine Cantonese in eng->yue direction: GLM={gq:.1f}  Qwen={qq:.1f}")

    wins = (delta["COMET-22"] > 0.01).sum()
    print("\nSuggested reading of the evidence:")
    if wins >= 3 and gq >= qq + 5:
        print("→ REPLACE Qwen2.5: GLM wins on quality AND authenticity.")
    elif wins >= 2 or gq >= qq + 5:
        print("→ ADOPT ALONGSIDE Qwen2.5: complementary strengths; route by direction.")
    elif wins == 0 and gq < 30:
        print("→ RULE OUT: no metric advantage and mostly Mandarin-in-Traditional output.")
    else:
        print("→ Marginal case — inspect per-direction results and examples above.")
decide()

model          direction  chrF  COMET-22
  glm eng_Latn->yue_Hant 21.14    0.7917
  glm eng_Latn->zho_Hans 36.80    0.8752
  glm yue_Hant->eng_Latn 57.25    0.8630
  glm zho_Hans->eng_Latn 58.53    0.8703
 qwen eng_Latn->yue_Hant 13.13    0.6747
 qwen eng_Latn->zho_Hans 32.47    0.8327
 qwen yue_Hant->eng_Latn 54.32    0.8365
 qwen zho_Hans->eng_Latn 54.03    0.8368

model          direction  % genuine Cantonese  % Mandarin-in-Trad  % mixed  % neutral  (ref % Cantonese)
  glm eng_Latn->yue_Hant                 93.5                 0.5      0.5        5.5                0.0
 qwen eng_Latn->yue_Hant                 82.0                 3.0      4.0       11.0                0.0

GLM minus Qwen2.5 (positive = GLM better):
                    chrF  COMET-22
direction
eng_Latn->yue_Hant  8.01     0.117
eng_Latn->zho_Hans  4.33     0.042
yue_Hant->eng_Latn  2.93     0.026
zho_Hans->eng_Latn  4.50     0.033

%% genuine Cantonese in eng->yue direction: GLM=93.5  Qwen=82.0

Suggested reading of the evidence:
→ REPLACE Qwen2.5: GLM wins on quality AND authenticity.

In [13]:
#@title 9. Push to GitHub
GH_USER = "srinayani123"      #@param {type:"string"}
GH_REPO = "vosyn--supernova--project_sprint47" #@param {type:"string"}

from google.colab import userdata
import subprocess, shutil, glob, sys

def git(*args, check=True):
    r = subprocess.run(["git", "-C", work, *args],
                       capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.returncode and r.stderr.strip(): print("STDERR:", r.stderr.strip())
    if check and r.returncode:
        raise RuntimeError(f"git {' '.join(args)} failed (exit {r.returncode})")
    return r

token = userdata.get("GITHUB_TOKEN")
assert token, "No GITHUB_TOKEN secret found — add it via the 🔑 panel on the left."
repo_url = f"https://{GH_USER}:{token}@github.com/{GH_USER}/{GH_REPO}.git"

work = "/content/_push"
shutil.rmtree(work, ignore_errors=True)

# Clone if the repo already has commits; otherwise init a fresh repo.
clone = subprocess.run(["git", "clone", repo_url, work],
                       capture_output=True, text=True)
if clone.returncode:
    print("Clone failed (likely an empty repo) — initializing fresh.")
    subprocess.run(["git", "init", work], check=True)
    git("remote", "add", "origin", repo_url)

# Copy the deliverables in.
shutil.copytree("outputs", f"{work}/outputs", dirs_exist_ok=True)
for pat in ("/content/*.ipynb", "/content/*.md"):
    for f in glob.glob(pat):
        shutil.copy(f, work)

git("config", "user.email", f"{GH_USER}@users.noreply.github.com")
git("config", "user.name", GH_USER)
git("checkout", "-B", "main")          # force branch name to main
git("add", "-A")

commit = git("commit", "-m", "GLM Cantonese FLORES-200 evaluation results", check=False)
if "nothing to commit" in (commit.stdout + commit.stderr):
    print("Nothing new to commit — files already up to date.")

git("push", "-u", "origin", "main")
print(f"\n✅ Done → share with the team: https://github.com/{GH_USER}/{GH_REPO}")

[main (root-commit) ed30019] GLM Cantonese FLORES-200 evaluation results
 10 files changed, 4876 insertions(+)
 create mode 100644 outputs/cantonese_authenticity.csv
 create mode 100644 outputs/glm_eng_Latn_yue_Hant.json
 create mode 100644 outputs/glm_eng_Latn_zho_Hans.json
 create mode 100644 outputs/glm_yue_Hant_eng_Latn.json
 create mode 100644 outputs/glm_zho_Hans_eng_Latn.json
 create mode 100644 outputs/qwen_eng_Latn_yue_Hant.json
 create mode 100644 outputs/qwen_eng_Latn_zho_Hans.json
 create mode 100644 outputs/qwen_yue_Hant_eng_Latn.json
 create mode 100644 outputs/qwen_zho_Hans_eng_Latn.json
 create mode 100644 outputs/scores.csv
STDERR: remote: Permission to srinayani123/vosyn--supernova--project_sprint47.git denied to srinayani123.
fatal: unable to access 'https://github.com/srinayani123/vosyn--supernova--project_sprint47.git/': The requested URL returned error: 403

RuntimeError: git push -u origin main failed (exit 128)

In [14]:
from google.colab import userdata
import subprocess

GH_USER = "srinayani123"
GH_REPO = "vosyn--supernova--project_sprint47"
work = "/content/_push"

token = userdata.get("GITHUB_TOKEN")   # picks up the NEW token
repo_url = f"https://{GH_USER}:{token}@github.com/{GH_USER}/{GH_REPO}.git"

subprocess.run(["git", "-C", work, "remote", "set-url", "origin", repo_url], check=True)
r = subprocess.run(["git", "-C", work, "push", "-u", "origin", "main"],
                   capture_output=True, text=True)
print(r.stdout)
print(r.stderr)
if r.returncode == 0:
    print(f"\n✅ Pushed → https://github.com/{GH_USER}/{GH_REPO}")

Branch 'main' set up to track remote branch 'main' from 'origin'.

To https://github.com/srinayani123/vosyn--supernova--project_sprint47.git
 * [new branch]      main -> main


✅ Pushed → https://github.com/srinayani123/vosyn--supernova--project_sprint47

In [ ]:
from google.colab import files
import shutil, subprocess, glob, os

work = "/content/_push"

# 1. Upload the notebook + any .md reports from your computer.
#    (In Colab: File → Download → Download .ipynb first, then pick it here.)
print("Select your .ipynb (and any .md files) to upload:")
uploaded = files.upload()          # opens a file picker

# 2. Move them into the repo clone.
for fname in uploaded:
    shutil.copy(fname, work)
    print("added:", fname)

# 3. Commit and push.
def git(*a):
    r = subprocess.run(["git", "-C", work, *a], capture_output=True, text=True)
    print(r.stdout or "", r.stderr or "")
    return r

git("add", "-A")
git("commit", "-m", "Add evaluation notebook and reports")
git("push", "origin", "main")
print("\n✅ Refresh the repo page — the .ipynb should now be there.")

Select your .ipynb (and any .md files) to upload: